### ISSUE TITLE
Does this handle Marshmallow stuff?

### ISSUE THREAD

**Issue by fat-tire** [PrashamTrivedi/AndroidExternalFileWriter#3]
I'm thinking particularly re: (1) the new runtime permissions model and (2) any changes required to handle [adoptable external storage](http://www.androidpolice.com/2015/05/28/android-m-feature-spotlight-external-storage-can-be-adopted-as-true-internal-storage-or-accessed-normally-with-no-additional-apps/)....

**Comment by PrashamTrivedi** [comment]
No, current version does not include anything M related stuffs. I have not
even started working on it, infact I am catching the M train...

It will (obviously) going to take time(the learning process, finishing
current works). Meanwhile if you come up any solutions. PRs are welcome.

**Comment by PrashamTrivedi** [comment]
From API 21+ we don't need permissions. Based on Ian Lake's talk on Big Android BBQ 2015, I am preparing new version to work around that, with help of Storage Access framework. I invite you and others to try our new 2.0-Snapshot version. Please check releases and give your feedback..

P.S.: I will update links later tomorrow. Thanks
